import React, { useState } from 'react';
import {
  Wrench,
  CheckCircle,
  Clock,
  Sparkles,
  TrendingUp,
  ShieldCheck,
  AlertCircle,
  Truck,
  Flame,
  CloudRain,
  Calendar,
  Loader2,
} from 'lucide-react';
import { CorrectiveActionItem } from '../types';
import { getGeminiHeaders, getSelectedModel } from '../lib/geminiApi';

interface CorrectiveActionsViewProps {
  initialActions: CorrectiveActionItem[];
}

export const CorrectiveActionsView: React.FC<CorrectiveActionsViewProps> = ({
  initialActions,
}) => {
  const [actions, setActions] = useState<CorrectiveActionItem[]>(initialActions);
  const [isGeneratingAi, setIsGeneratingAi] = useState(false);
  const [customDiagnostic, setCustomDiagnostic] = useState<string | null>(null);

  const toggleActionStatus = (id: string) => {
    setActions((prev) =>
      prev.map((a) => {
        if (a.id === id) {
          const newStatus = a.status === 'Applied' ? 'Recommended' : 'Applied';
          return { ...a, status: newStatus };
        }
        return a;
      })
    );
  };

  const appliedActions = actions.filter((a) => a.status === 'Applied');
  const totalRecoveredTonnage = appliedActions.reduce(
    (acc, a) => acc + a.impactRecoveryMT,
    0
  );
  const baseShortfall = 750;
  const netShortfall = Math.max(0, baseShortfall - totalRecoveredTonnage);
  const targetCoveragePercent = Math.min(
    100,
    ((totalRecoveredTonnage) / baseShortfall) * 100
  );

  const handleGenerateFreshAiActions = async () => {
    setIsGeneratingAi(true);
    try {
      const res = await fetch('/api/gemini/shortfall-prediction', {
        method: 'POST',
        headers: getGeminiHeaders(),
        body: JSON.stringify({
          mineSite: 'Balaghat Mine, MP',
          currentTargetMT: 3500,
          actualProducedMT: 2750,
          model: getSelectedModel(),
          constraints: {
            weather: '46.5mm monsoon rainfall, haul road slurry speed reduced',
            equipment: 'Excavator EX-04 down for 14h, 6 dumpers delayed',
            blasting: 'Township boundary ground vibration constraint (PPV < 5 mm/s)',
          },
        }),
      });
      const data = await res.json();
      if (data.diagnosis) {
        setCustomDiagnostic(data.diagnosis);
      }
      if (data.correctiveActions && Array.isArray(data.correctiveActions)) {
        const newItems: CorrectiveActionItem[] = data.correctiveActions.map(
          (item: any, i: number) => ({
            id: `ai-act-${Date.now()}-${i}`,
            title: item.action,
            description: item.impact,
            category: 'Equipment Redeployment',
            impactRecoveryMT: 250 + i * 120,
            urgency: item.urgency || 'Immediate',
            costRupees: '₹22,000 (Dispatch optimization)',
            status: 'Recommended',
            rationale: 'Generated by Gemini 3.8 Flash model based on active shift telematics.',
          })
        );
        setActions((prev) => [...newItems, ...prev]);
      }
    } catch (e) {
      console.error(e);
    } finally {
      setIsGeneratingAi(false);
    }
  };

  return (
    <div
      id="corrective-actions-view"
      className="p-6 space-y-6 max-w-[1600px] mx-auto"
    >
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-white p-5 rounded-xl border border-slate-200/90 shadow-xs">
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-lg bg-blue-50 text-blue-600">
            <Wrench className="w-5 h-5" />
          </div>
          <div>
            <h2 className="text-lg font-bold text-slate-900 tracking-tight">
              AI Corrective Actions & Mine Schedule Optimizer
            </h2>
            <p className="text-xs text-slate-500">
              Prescriptive operational adjustments to mitigate production shortfalls and sustain steady ore supply
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={async () => {
              try {
                const res = await fetch('/api/shortfalls/scenarios', {
                  method: 'POST',
                  headers: { 'Content-Type': 'application/json' },
                  body: JSON.stringify({
                    name: `Shift Plan (${new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })})`,
                    projectedShortfallMT: baseShortfall,
                    recoveredTonnageMT: totalRecoveredTonnage,
                    appliedInterventions: appliedActions.map((a) => a.title),
                    author: 'Operations Director',
                  }),
                });
                if (res.ok) {
                  alert('Shortfall mitigation scenario saved to MOIL Geodatabase!');
                }
              } catch (e) {
                console.error(e);
              }
            }}
            className="cursor-pointer inline-flex items-center gap-1.5 px-3 py-2 rounded-lg bg-emerald-50 hover:bg-emerald-100 text-emerald-800 border border-emerald-200 text-xs font-semibold transition-colors"
            title="Save scenario to persistent database"
          >
            <CheckCircle className="w-3.5 h-3.5 text-emerald-600" />
            <span>Save to Geodatabase</span>
          </button>

          <button
            onClick={handleGenerateFreshAiActions}
            disabled={isGeneratingAi}
            className="cursor-pointer inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-blue-600 hover:bg-blue-700 text-white text-xs font-semibold shadow-xs transition-colors disabled:opacity-50"
          >
            {isGeneratingAi ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                <span>Optimizing Shift Dispatch...</span>
              </>
            ) : (
              <>
                <Sparkles className="w-4 h-4" />
                <span>Run Gemini AI Dispatch Optimizer</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* Real-Time Shortfall Mitigation Simulator Banner */}
      <div className="bg-slate-900 text-white p-5 rounded-xl border border-slate-800 shadow-md space-y-3">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <div>
            <span className="text-[11px] font-bold uppercase tracking-wider text-blue-400">
              Live Shortfall Mitigation Simulator
            </span>
            <div className="text-sm font-medium text-slate-300 mt-0.5">
              Toggle actions below to simulate instant production recovery
            </div>
          </div>

          <div className="flex items-center gap-6">
            <div>
              <div className="text-[10px] text-slate-400">Base Shortfall</div>
              <div className="text-lg font-bold text-red-400 font-mono">
                -{baseShortfall} MT
              </div>
            </div>
            <div>
              <div className="text-[10px] text-slate-400">Recovered Ore</div>
              <div className="text-lg font-bold text-emerald-400 font-mono">
                +{totalRecoveredTonnage} MT
              </div>
            </div>
            <div>
              <div className="text-[10px] text-slate-400">Net Deficit</div>
              <div
                className={`text-lg font-bold font-mono ${
                  netShortfall === 0 ? 'text-emerald-400' : 'text-amber-400'
                }`}
              >
                {netShortfall === 0 ? '0 MT (Fully Resolved!)' : `-${netShortfall} MT`}
              </div>
            </div>
          </div>
        </div>

        {/* Progress Bar of Deficit Offset */}
        <div className="space-y-1">
          <div className="flex justify-between text-[11px] font-mono text-slate-400">
            <span>Recovery Coverage</span>
            <span className="font-bold text-emerald-400">
              {targetCoveragePercent.toFixed(1)}% Recovered
            </span>
          </div>
          <div className="w-full h-3 bg-slate-800 rounded-full overflow-hidden">
            <div
              className="h-full bg-gradient-to-r from-blue-500 to-emerald-500 transition-all duration-300"
              style={{ width: `${targetCoveragePercent}%` }}
            ></div>
          </div>
        </div>
      </div>

      {customDiagnostic && (
        <div className="p-4 bg-blue-50 border border-blue-200 rounded-xl text-xs text-blue-900 flex items-start gap-3">
          <Sparkles className="w-5 h-5 text-blue-600 shrink-0 mt-0.5" />
          <div>
            <div className="font-bold mb-0.5">AI Operations Diagnostic:</div>
            <p>{customDiagnostic}</p>
          </div>
        </div>
      )}

      {/* Recommended Corrective Action Cards */}
      <div className="space-y-3">
        <h3 className="text-xs font-bold uppercase tracking-wider text-slate-700 flex items-center gap-2">
          <ShieldCheck className="w-4 h-4 text-blue-600" />
          Recommended Operational Interventions ({actions.length})
        </h3>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {actions.map((act) => {
            const isApplied = act.status === 'Applied';

            const getCategoryIcon = () => {
              switch (act.category) {
                case 'Equipment Redeployment':
                  return <Truck className="w-5 h-5 text-purple-600" />;
                case 'Blasting Optimization':
                  return <Flame className="w-5 h-5 text-rose-600" />;
                case 'Dewatering':
                  return <CloudRain className="w-5 h-5 text-blue-600" />;
                default:
                  return <Calendar className="w-5 h-5 text-amber-600" />;
              }
            };

            return (
              <div
                key={act.id}
                className={`bg-white rounded-xl border p-5 shadow-xs transition-all space-y-3 ${
                  isApplied
                    ? 'border-emerald-500 bg-emerald-50/20 ring-1 ring-emerald-500'
                    : 'border-slate-200/90 hover:border-slate-300'
                }`}
              >
                <div className="flex items-start justify-between gap-3">
                  <div className="flex items-start gap-3">
                    <div className="p-2 rounded-lg bg-slate-50 border border-slate-200 mt-0.5">
                      {getCategoryIcon()}
                    </div>
                    <div>
                      <h4 className="text-sm font-bold text-slate-900 leading-snug">
                        {act.title}
                      </h4>
                      <div className="flex items-center gap-2 mt-1">
                        <span className="text-[10px] font-semibold text-slate-500">
                          {act.category}
                        </span>
                        <span className="text-slate-300">•</span>
                        <span className="text-[10px] font-bold text-amber-700 bg-amber-50 px-1.5 py-0.2 rounded">
                          Urgency: {act.urgency}
                        </span>
                      </div>
                    </div>
                  </div>

                  <span
                    className={`text-[10px] font-bold px-2 py-0.5 rounded-full ${
                      isApplied
                        ? 'bg-emerald-100 text-emerald-800'
                        : 'bg-slate-100 text-slate-700'
                    }`}
                  >
                    {act.status}
                  </span>
                </div>

                <p className="text-xs text-slate-600 leading-relaxed">
                  {act.description}
                </p>

                <div className="p-2.5 bg-slate-50 rounded-lg border border-slate-200/70 text-[11px] text-slate-700 space-y-1">
                  <div>
                    <strong>Operational Rationale:</strong> {act.rationale}
                  </div>
                  <div className="text-slate-500">
                    Estimated Implementation Cost: {act.costRupees}
                  </div>
                </div>

                <div className="pt-2 border-t border-slate-100 flex items-center justify-between">
                  <div className="text-xs">
                    <span className="text-slate-500">Tonnage Recovery:</span>{' '}
                    <span className="font-extrabold text-emerald-600">
                      +{act.impactRecoveryMT} MT
                    </span>
                  </div>

                  <button
                    onClick={() => toggleActionStatus(act.id)}
                    className={`cursor-pointer px-3.5 py-1.5 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-colors ${
                      isApplied
                        ? 'bg-slate-200 hover:bg-slate-300 text-slate-700'
                        : 'bg-emerald-600 hover:bg-emerald-700 text-white shadow-2xs'
                    }`}
                  >
                    <CheckCircle className="w-3.5 h-3.5" />
                    <span>{isApplied ? 'Revert Action' : 'Apply Dispatch Action'}</span>
                  </button>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
};
